travis:
  secure:
    BINSTAR_TOKEN: dOkJf7UGMB5qupHp9I1pxYCaRsXXiEodYe+Zg2N2GEKMprR8arYMxdf8i7L8mwF2ITLjACYyCnIsNKWxzGzTuty/ahqPb2a17NUcmNOaIyLG7NB2DciXJAC5YO/CXExL/i7ttZx5esQ1TzajLL7XBEmTy/K7fiSrIioS2PMinXaONCE4cqUv8N7n2ib4AUL9L7v2lpYMnB/WCEGB81sF9T+CWAnbZl6LIxev1GSSQsLExYOa8QZIZly/CcJ3Hx8SCZXNMjy+P4FcuSl9HbVXXKj7X4+pSE7x5zhN4RlRJmk2WCMHnUMkP6LHWqkKvZPN+5KBQhvu3emZGymk/B8bshL/+R3zG918iKuLR3fgx+fqzr8v/jXi6HgcuG/aP6hHh5xNG5Abs/TTesm3PQ54aB7JVDXx9sJYSvhNRpStrRB6kGXon0qJOCmVoeKkGYmnMqIomcQdx0wPDmRtpgQBrRlnW+JsztcCOzZv+L8Bw9uByZbFGVY5iYp7RgWnnLkEEMdY6YkzTn8yz7/QK2S0n0vP5nlp0u0AnNSk7nPN2dXBGI+J9F+YnvfFj+l4cK262VXf1wzSMGx0UaKNdg/CVD4ArxSKLhB1Nrgrqn4tHYeifoR4Omc5u9knuk7HUMvj0roUpYO7UNl0HfrFq+EZR8ViDoQ33Q3qaSnaqhosGRg=
provider: {win: azure}
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
bot:
  automerge: true
